//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeysPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RentalApplication()
        {
            this.RentalApplicationMedia = new HashSet<RentalApplicationMedia>();
        }
    
        public int Id { get; set; }
        public int RentalListingId { get; set; }
        public int PersonId { get; set; }
        public string Note { get; set; }
        public Nullable<int> TenantsCount { get; set; }
        public int ApplicationStatusId { get; set; }
        public string TenantIdType { get; set; }
        public string TenantIdNo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsViewedByOwner { get; set; }
    
        public virtual RentalApplicationStatus RentalApplicationStatus { get; set; }
        public virtual RentalListing RentalListing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentalApplicationMedia> RentalApplicationMedia { get; set; }
        public virtual Person Person { get; set; }
    }
}
